import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="relative min-h-screen pb-14">
          {children}
          <nav className="fixed bottom-0 left-0 right-0 h-14 bg-black border-t border-gray-200 shadow z-50 flex items-center justify-around">
            <Link href="/">Home</Link>
            <Link href="/events">Events</Link>
          </nav>
        </div>
      </body>
    </html>
  );
}